# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 07:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20171016_0036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address',
            new_name='itemDesc',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='itemName',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='itemPrice',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='status',
            new_name='itemQty',
        ),
    ]
